import React from 'react';
import SEO from '../../components/common/SEO';
import Breadcrumb from '../../components/common/Breadcrumb';

const Terms = () => {
  const breadcrumbItems = [{ label: 'Terms of Use', path: '/terms' }];

  return (
    <>
      <SEO
        title="Terms of Use"
        description="Terms of use policies, liability limitations, and solicitations guidelines at DoConnect."
        keywords="terms of use, corporate disclaimers, insurance guidelines, doconnect"
        path="/terms"
      />

      <div className="bg-slate-50 border-b border-slate-100 py-10">
        <div className="max-w-7xl mx-auto px-6">
          <Breadcrumb items={breadcrumbItems} />
          <h1 className="font-display font-extrabold text-3xl text-dark mt-2">
            Terms of Use
          </h1>
          <p className="text-slate-500 text-xs md:text-sm mt-1">
            Last Updated: July 07, 2026
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-12 text-slate-600 text-sm md:text-base leading-relaxed space-y-8">
        <p className="lead text-slate-700 text-base md:text-lg font-medium">
          Welcome to DoConnect (&quot;Platform&quot;). These Terms of Use govern your access to and use of websites, mobile applications, and services owned and operated by DoConnect Insurance Brokers Private Limited (hereinafter referred to as &quot;DoConnect&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot;).
        </p>

        <p>
          By accessing or using our Platform, you acknowledge that you have read, understood, and agreed to be bound by these Terms of Use and our Privacy Policy. If you do not agree to these terms, please do not access or use our Platform or avail any of our services.
        </p>

        <div className="bg-slate-50 border border-slate-100 rounded-2xl p-6 space-y-4">
          <h3 className="font-display font-bold text-dark text-sm uppercase tracking-wider text-slate-800">
            1. Eligibility & Acceptance
          </h3>
          <p>
            You must be at least 18 years of age and competent to contract under the Indian Contract Act, 1872 to use our Platform. By accessing the Platform, you represent and warrant that you possess the legal authority to enter into a binding agreement and that all registration and application information you submit is accurate and truthful.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            2. Platform Services & Solicitation Disclaimer
          </h3>
          <p>
            DoConnect acts as an independent digital insurance search, comparison, and advisory interface. Insurance products listed on this website are the subject matter of solicitation. All insurance contracts, premiums, coverages, exclusions, and claims are subject to the terms and guidelines of the respective insurance underwriting company.
          </p>
          <p>
            We do not underwrite insurance policies directly. Your purchase of an insurance policy is a contract solely between you (the policyholder) and the underwriting insurance company.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            3. Accuracy of Premium Estimations & Quotes
          </h3>
          <p>
            All premium estimates, quotes, and comparison details generated by our interactive widgets (such as the premium calculator) are based on generic IRDAI basic tariff sheets and are intended for illustrative comparison purposes only.
          </p>
          <p>
            Exact premium values, policy loadings, discounts, and underwriting approvals are determined dynamically by the respective insurance company after assessing your actual medical history, vehicle details, declarations, and pre-acceptance diagnostic tests (where applicable).
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            4. Payments & Transactions
          </h3>
          <p>
            Any payment made for the purchase of insurance policies through the Platform is processed directly by the respective insurance company or through authorized third-party payment gateways. DoConnect does not collect or store credit/debit card numbers or other sensitive financial credentials.
          </p>
          <p>
            The processing of payments is governed by the terms and policies of the respective payment gateway providers and insurers, and DoConnect shall not be liable for transactions that fail or are delayed at their end.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            5. Intellectual Property Rights
          </h3>
          <p>
            All content, layout, designs, logos, graphics, icons, text, calculators, software code, and databases on this Platform are the intellectual property of DoConnect Insurance Brokers Private Limited, protected under applicable trademark, copyright, and database rights laws of India. You may not copy, extract, reproduce, distribute, or modify any part of our Platform without our prior written consent.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            6. Limitation of Liability
          </h3>
          <p>
            DoConnect acts solely as a digital broker and comparison facilitator. We shall not be held liable for any claims, losses, rejections, waiting period disputes, or service deficiencies arising between you and the insurance underwriting company.
          </p>
          <p>
            Final policy purchase approvals, claim clearances, cashless hospital networks, and renewals are handled directly under the sole discretion and jurisdiction of the respective insurer.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            7. Indemnification
          </h3>
          <p>
            You agree to defend, indemnify, and hold harmless DoConnect, its directors, employees, and affiliates from and against any claims, liabilities, losses, damages, or costs (including legal fees) arising out of your misuse of the Platform, violation of these Terms of Use, or infringement of any intellectual property rights.
          </p>
        </div>

        <div className="space-y-4">
          <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
            8. Governing Law & Jurisdiction
          </h3>
          <p>
            These Terms of Use and your usage of the Platform are governed by and construed in accordance with the laws of India. Any legal actions, claims, or disputations concerning these services shall be subject to the exclusive jurisdiction of the competent courts in Noida, Uttar Pradesh, India.
          </p>
        </div>

        <div className="space-y-6 pt-6 border-t border-slate-100">
          <h3 className="font-display font-extrabold text-dark text-lg uppercase tracking-wider">
            Customer Support & Grievances
          </h3>
          <p>
            If you have any questions, feedback, or complaints regarding these Terms of Use, please reach out to our grievance redressal officer:
          </p>

          <div className="bg-slate-50 border border-slate-100 rounded-2xl p-6 space-y-3 font-medium text-slate-700 text-xs md:text-sm max-w-xl text-left">
            <p><span className="text-slate-400 font-normal block text-[10px] uppercase tracking-wider">Name</span> Mr. Shubham Chauhan</p>
            <p><span className="text-slate-400 font-normal block text-[10px] uppercase tracking-wider">Address</span> B-52, Block - B Sector - 64 Noida 201301, Uttar Pradesh, India</p>
            <p>
              <span className="text-slate-400 font-normal block text-[10px] uppercase tracking-wider">E-mail</span> 
              <a href="mailto:grievance@doconnectservices.com" className="text-primary hover:underline">grievance@doconnectservices.com</a>
            </p>
            <p>
              <span className="text-slate-400 font-normal block text-[10px] uppercase tracking-wider">Telephone Number</span> 
              <a href="tel:+917683098648" className="text-primary hover:underline">+91 76830 98648</a>
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Terms;
