import React from 'react';
import SEO from '../../components/common/SEO';
import Breadcrumb from '../../components/common/Breadcrumb';

const Terms = () => {
  const breadcrumbItems = [{ label: 'Terms of Use', path: '/terms' }];

  return (
    <>
      <SEO
        title="Terms of Use"
        description="Terms of use policies, liability limitations, and solicitations guidelines at SecureHealth."
        keywords="terms of use, corporate disclaimers, insurance guidelines"
        path="/terms"
      />

      <div className="bg-slate-50 border-b border-slate-100 py-10">
        <div className="max-w-7xl mx-auto px-6">
          <Breadcrumb items={breadcrumbItems} />
          <h1 className="font-display font-extrabold text-3xl text-dark mt-2">
            Terms of Use
          </h1>
          <p className="text-slate-500 text-xs md:text-sm mt-1">
            Last Updated: July 07, 2026
          </p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-12 text-slate-600 text-sm md:text-base leading-relaxed space-y-6">
        <p>
          Welcome to SecureHealth. By accessing our website, you agree to comply with and be bound by the following terms of use. Please read these terms carefully before using our services.
        </p>

        <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
          1. Solicitation Disclaimer
        </h3>
        <p>
          SecureHealth acts as an independent health insurance search, comparison, and advisory interface. Health insurance products listed on this website are the subject matter of solicitation. All insurance contracts, premiums, coverages, exclusions, and claims are subject to the terms and guidelines of the respective insurance underwriting company. We do not underwrite insurance policies directly.
        </p>

        <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
          2. Accuracy of Premium Estimations
        </h3>
        <p>
          All premium estimates generated by our interactive widgets (such as the premium calculator) are based on generic IRDAI basic tariff sheets and are intended for illustrative comparison purposes only. Exact premium values, loadings, and underwriting approvals are determined dynamically by the insurance company after assessing medical history and pre-acceptance diagnostic tests.
        </p>

        <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
          3. Limitation of Liability
        </h3>
        <p>
          SecureHealth shall not be held liable for any claims, losses, rejections, or disputations arising between the policyholder and the insurance company. We act solely as a facilitator and comparison portal. Final policy purchase approvals, claim clearances, and renewals are handled directly under the jurisdiction of the insurer.
        </p>

        <h3 className="font-display font-bold text-dark text-lg pt-4 border-b border-slate-100 pb-2">
          4. Governing Law
        </h3>
        <p>
          These terms are governed by and construed in accordance with the laws of India. Any legal action or disputations concerning these services shall be subject to the exclusive jurisdiction of the courts in Gurugram, Haryana.
        </p>
      </div>
    </>
  );
};

export default Terms;
