import resend, { isMockMode } from '../config/resend.js';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Service to handle email sending logic via Resend
 */
class EmailService {
  /**
   * Send customer enquiry details to Doconnect business email
   * @param {Object} enquiry - Enquiry data { name, email, phone, service, message }
   */
  async sendBusinessEnquiryEmail(enquiry) {
    const { name, email, phone, service, message } = enquiry;
    const businessEmail = process.env.BUSINESS_EMAIL || 'your-business-email@example.com';
    const fromEmail = process.env.FROM_EMAIL || 'onboarding@resend.dev';
    const submissionTime = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

    const emailOptions = {
      from: `Doconnect Services <${fromEmail}>`,
      to: businessEmail,
      subject: `New Customer Enquiry — Doconnect Services`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #dceaf4; border-radius: 12px; background-color: #fcfdfe;">
          <div style="text-align: center; margin-bottom: 20px;">
            <span style="font-size: 20px; font-weight: bold; color: #2F6FAF; letter-spacing: 0.5px;">DOCONNECT SERVICES</span>
          </div>
          <h2 style="color: #16324F; border-bottom: 2px solid #2F6FAF; padding-bottom: 10px; margin-top: 0; font-size: 18px;">New Customer Enquiry</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64798D; width: 35%;">Name:</td>
              <td style="padding: 8px 0; color: #16324F;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64798D;">Email:</td>
              <td style="padding: 8px 0; color: #16324F;"><a href="mailto:${email}" style="color: #2F6FAF; text-decoration: none;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64798D;">Phone:</td>
              <td style="padding: 8px 0; color: #16324F;"><a href="tel:${phone}" style="color: #2F6FAF; text-decoration: none;">${phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64798D;">Service:</td>
              <td style="padding: 8px 0; color: #16324F; font-weight: bold;">${service}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #64798D;">Submitted:</td>
              <td style="padding: 8px 0; color: #16324F;">${submissionTime}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #eaf6fc; border-radius: 8px; border-left: 4px solid #2F6FAF;">
            <strong style="color: #16324F; display: block; margin-bottom: 5px;">Message:</strong>
            <p style="color: #16324F; margin: 0; line-height: 1.5; white-space: pre-wrap;">${message}</p>
          </div>
          <div style="margin-top: 25px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            This email was automatically generated by the Doconnect Services web portal backend using Resend.
          </div>
        </div>
      `,
    };

    if (isMockMode) {
      this._logMockEmail('Business Enquiry Alert', emailOptions);
      return { isMock: true };
    }

    const { data, error } = await resend.emails.send(emailOptions);
    if (error) {
      throw new Error(`Resend sendBusinessEnquiryEmail error: ${error.message || JSON.stringify(error)}`);
    }
    return data;
  }

  /**
   * Send thank-you/acknowledgement email to the customer
   * @param {string} name - Customer name
   * @param {string} email - Customer email
   */
  async sendCustomerThankYouEmail(name, email) {
    const fromEmail = process.env.FROM_EMAIL || 'onboarding@resend.dev';

    const emailOptions = {
      from: `Doconnect Services <${fromEmail}>`,
      to: email,
      subject: `Thank You for Contacting Doconnect Services`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #dceaf4; border-radius: 12px; background-color: #fcfdfe;">
          <div style="text-align: center; margin-bottom: 25px;">
            <span style="font-size: 22px; font-weight: bold; color: #2F6FAF; letter-spacing: 0.5px;">Doconnect Services</span>
          </div>
          <p style="font-size: 15px; color: #16324F; line-height: 1.5; margin-bottom: 12px;">Hi ${name},</p>
          <p style="font-size: 15px; color: #16324F; line-height: 1.5; margin-bottom: 12px;">Thank you for contacting Doconnect Services.</p>
          <p style="font-size: 15px; color: #16324F; line-height: 1.5; margin-bottom: 12px;">We have successfully received your enquiry and our team is currently reviewing your request.</p>
          <p style="font-size: 15px; color: #16324F; line-height: 1.5; margin-bottom: 12px;">One of our representatives will connect with you within <strong>24 hours</strong>.</p>
          <p style="font-size: 15px; color: #16324F; line-height: 1.5; margin-bottom: 20px;">We appreciate your interest in Doconnect Services and look forward to assisting you.</p>
          
          <div style="margin-top: 25px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 14px; color: #64798D;">
            Regards,<br />
            <strong>Doconnect Services Team</strong>
          </div>
        </div>
      `,
    };

    if (isMockMode) {
      this._logMockEmail('Customer Thank-You Receipt', emailOptions);
      return { isMock: true };
    }

    const { data, error } = await resend.emails.send(emailOptions);
    if (error) {
      throw new Error(`Resend sendCustomerThankYouEmail error: ${error.message || JSON.stringify(error)}`);
    }
    return data;
  }

  /**
   * Helper to print simulated emails in mock mode
   */
  _logMockEmail(label, options) {
    console.log('\n----------------------------------------------------');
    console.log(`📧 [MOCK EMAIL VIA RESEND - ${label}]`);
    console.log(`To: ${options.to}`);
    console.log(`Subject: ${options.subject}`);
    console.log(`From: ${options.from}`);
    console.log(`Body Snippet: ${options.html.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').substring(0, 180)}...`);
    console.log('----------------------------------------------------\n');
  }
}

export default new EmailService();
